# Generated by Django 4.0.5 on 2022-10-22 22:14

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multipedia', '0004_alter_search_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterSearch',
            fields=[
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='twitter_search', serialize=False, to='multipedia.search')),
                ('title', models.CharField(max_length=200)),
                ('tweets', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Twiiter Searches',
            },
        ),
    ]
