# Generated by Django 4.0.5 on 2022-10-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearch',
            name='phonetic',
            field=models.CharField(default='hey', max_length=200),
            preserve_default=False,
        ),
    ]
