# Generated by Django 4.0.5 on 2022-10-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twittersearch',
            options={'verbose_name_plural': 'Twitter Searches'},
        ),
    ]
