# Generated by Django 4.0.5 on 2022-06-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urbansearch',
            old_name='term',
            new_name='search',
        ),
    ]
