# Generated by Django 3.2.7 on 2022-06-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0002_rename_term_urbansearch_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urbansearch',
            options={'verbose_name_plural': 'Urban Searches'},
        ),
    ]
