# Generated by Django 4.0.5 on 2022-06-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multipedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanSearch',
            fields=[
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='multipedia.search')),
                ('word', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
    ]
