# Generated by Django 4.0.5 on 2022-10-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multipedia', '0004_alter_search_slug'),
        ('urban', '0004_alter_urbansearch_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbansearch',
            name='search',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='multipedia.search'),
        ),
    ]
