# Generated by Django 4.0.5 on 2022-06-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipedia', '0002_alter_search_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='slug',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
    ]
