# Generated by Django 3.2.7 on 2022-06-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
